redis: &redis
  adapter: redis
  ur: redis://:pb9dbcfaccf2bfacc1bde03976ee601b2adc3fdbe3802ce3fa6ad9df751a1bdd7@ec2-34-205-188-48.compute-1.amazonaws.com:30599

production: *redis

redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: *redis
test: *redis
